import Footbar from "./_components/(main)/Footbar";
import Navbar from "./_components/(main)/Navbar";
import StyledComponentsRegistry from "./registry";

export const metadata = {
  title: "LGH Portfolio",
  description: "Generated by gwangholee",
  icons: {
    icon: {
      url: '/image/favicon.ico',
    }
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body style={{margin: '0px', width: '100%', height: '300%'}}>
        <Navbar></Navbar>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        <Footbar></Footbar>
      </body>
    </html>
  );
}