import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footbar from "./_components/Footbar";
import Navbar from "./_components/Navbar";
import StyledComponentsRegistry from "./registry";
import { Providers } from "./provider";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v14-appRouter';
config.autoAddCss = false;

export const metadata = {
  title: "LGH Portfolio",
  description: "Generated by gwangholee",
  icons: {
    icon: {
      url: '/image/favicon.ico',
    }
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body style={{margin: '0px', height: '300%'}}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Providers>
            <Navbar></Navbar>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            <Footbar></Footbar>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}